development:
  sessions:
    default:
      database: resocialbuilder_development
      hosts:
        - localhost:27017
  options:
    allow_dynamic_fields: true
    identity_map_enabled: false
    include_root_in_json: false

test:
  host: localhost
  database: resocialbuilder_test

# set these environment variables on your prod server
production:
  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: <%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
